apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: udagram
type: Opaque
data:
  aws_access_key_id: ASIAR4XNYGKJQDIU65GD
  aws_secret_access_key: apFB2DIstOoukJY1dc9xSkzMhBpH0r6rNl/xBSm6
  aws_session_token: FwoGZXIvYXdzEAwaDLuUrI9iPQxMxfX1aCK8AVNylTfRjYiZ9VrdTS8DYqlOjFy/vW05FWvwAGNfi85OntTWZ2wS9F/pC/P0R5yDp2A+tJRNHqcMBX3pmVEO9P+E6hXdOECvcFxH/FpPbr5JjQ/vivEi+anz/tA8kUSMZ4om2Ecg+5KD1qrjF/BD3cPz6Iv5DqWB5T+XqFY2neug40fM5bLFFUsgu6F34LF1C2IH05znDUfSXdIxghdL4Ta2uxjCm/qbGnsXbgAYAtgOTrX3BU1/S1TKign1KLDr/ZgGMi2eHkp60jLuRM2wD6a3XtyEhCa30aasMuitzesWBMMGvqCgo8huBmO6w9lYHik=
