apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  namespace: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: onealla/udagram-api-user:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2048Mi"
              cpu: "300m"
            limits:
              memory: "4096Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_USERNAME
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
