apiVersion: v1
kind: Service
metadata:
  name: backend-user
  namespace: udagram
spec:
  selector:
    app: backend-user
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
