apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  namespace: udagram
spec:
  selector:
    app: udagram-frontend
  ports:
    - name: "80"
      port: 8100
      protocol: TCP
      targetPort: http-svc
